name: Deploy to AWS
on:
  push:
    branches: [ "dev", "main" ]
permissions:
  contents: read
  pull-requests: write
jobs:
  deploy:
    name: deploy_to_aws
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_GITHUB }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_GITHUB }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          python3 -m pip install --upgrade pip
      - name: Install EB CLI
        run: |
          python3 -m pip install awsebcli

      - name: Deploy new version to EB
        run: |
          eb deploy Main-env --staged --timeout 20
          eb status Main-env
          eb health Main-env
